#!/usr/bin/env node

const pentf = require('./index.js');

const lockserver = require('./lockserver/lockserver');

pentf.main({
    rootDir: __dirname, // Mandatory
    // All further properties are optional
    beforeAllTests: lockserver.beforeAllTests,
    afterAllTests: lockserver.afterAllTests,
    description: 'Test pentf itself',
    defaultConfig: config => {
        // You can compute more complicated properties here. For example ...
        config.rejectUnauthorized = false; // Allow self-signed TLS certificates
        config.report_header_md = 'This is the end-to-end test report in *markdown* form.';
        config.report_header_html = 'This is the end-to-end test report in <strong>HTML/PDF</strong> form.';
    },
    noColors: true
});
