#!/usr/bin/env node

const pentf = require('../../src/index.js');
const { createPuppeteerLauncher } = require('../../src/plugins/puppeteer.js');
const { createServerPlugin } = require('../../src/plugins/server');

pentf.main({
    rootDir: __dirname,
    plugins: [
        createServerPlugin(),
        createPuppeteerLauncher()
    ]
});
