#!/usr/bin/env node

const pentf = require('../../src/index.js');
const { createSaucelabsLauncher } = require('../../src/plugins/saucelabs');
const { createServerPlugin } = require('../../src/plugins/server');

pentf.main({
    rootDir: __dirname,
    testsDir: __dirname,
    plugins: [
        createServerPlugin(),
        createSaucelabsLauncher({
            username: process.env.SAUCE_USERNAME,
            accessKey: process.env.SAUCE_ACCESS_KEY,
            browsers: [
                { name: 'chrome' }
            ]
        })
    ]
});
