name: Run tests
on: [push]

jobs:
  build:
    name: 'Node ${{ matrix.node-version }} with Puppeteer ${{ matrix.puppeteer-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, macos-latest]
        puppeteer-version: [22, 23, 24]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm install puppeteer@${{ matrix.puppeteer-version }}

      - name: Linux test
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get install ffmpeg
            xvfb-run --auto-servernum ./run --ci

      - run: make eslint
