name: Run tests
on: [push]

jobs:
  build:
    name: 'Node ${{ matrix.node-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - name: Linux test
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get install ffmpeg
            xvfb-run --auto-servernum ./run --ci

      - name: macOS test
        if: matrix.os == 'macOS-latest'
        run: |
            brew install ffmpeg
            ./run --ci

      - run: make eslint
      #- run: make prettier-lint
