name: Run tests
on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: make eslint

  test:
    name: 'Node ${{ matrix.node-version }} with Puppeteer ${{ matrix.puppeteer-version }} on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest, macos-latest]
        puppeteer-version: [24]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install puppeteer@${{ matrix.puppeteer-version }}
      - name: Run test
        #  run tests on Linux only. we only install on macos to verify that dependencies are compatible.
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          xvfb-run --auto-servernum ./run --ci
      - run: make eslint
